spring:
  datasource:
    url: jdbc:mysql://localhost:3306/develhopeDB
    username: semkok66
    password: Krevedk0!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

